### ISSUE TITLE
Run 2017 92X branch naming / 94X

### ISSUE THREAD

**Issue by garbersc** [UHH2/BaconJets#13]
Hi,
I think it would make sense to still use the 92X branch for the 2017 data processed with CMSSW 94X.
Maybe it should be renamed to a more fitting name?
Or do you think a new branch for the 17Nov2017 rereco more suitable?

**Comment by karavdin** [comment]
Hi Christoph,
I think we can create new branch for 94X/17Nov2017. Should it be based on RunII_2017_92X? Is RunII_2017_92X up to date in the repository?
Cheers,
Anastasia

**Comment by garbersc** [comment]
my side off the branch is up-to-date
